//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public solicitud()
        {
            this.documento = new HashSet<documento>();
        }
    
        public int idSolicitud { get; set; }
        public string asuntoSolicitud { get; set; }
        public int numRegSolicitud { get; set; }
        public System.DateTime fechaRecSolicitud { get; set; }
        public string obsSolicitud { get; set; }
        public string reqSolicitud { get; set; }
        public bool validacionReqSolicitud { get; set; }
        public bool estadoSolicitud { get; set; }
        public string atencionSolicitud { get; set; }
        public int idReqProc { get; set; }
        public int idEgresado { get; set; }
        public int idUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento> documento { get; set; }
        public virtual egresado egresado { get; set; }
        public virtual requisito_procedimiento requisito_procedimiento { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
