//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaFIMDBEntities : DbContext
    {
        public SistemaFIMDBEntities()
            : base("name=SistemaFIMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<documento> documento { get; set; }
        public virtual DbSet<egresado> egresado { get; set; }
        public virtual DbSet<facultad> facultad { get; set; }
        public virtual DbSet<nivel> nivel { get; set; }
        public virtual DbSet<procedimiento> procedimiento { get; set; }
        public virtual DbSet<requisito> requisito { get; set; }
        public virtual DbSet<requisito_procedimiento> requisito_procedimiento { get; set; }
        public virtual DbSet<responsable> responsable { get; set; }
        public virtual DbSet<solicitud> solicitud { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
